title: Hack the Threat 2023
logo: /logos/Hack%20the%20Threat%20Google%20form%20Header.png
description: <
  The Texas Advanced Computer Center (TACC) is partnering with Simon Fraser University (SFU) to offer an engaging virtual 
  Hackathon from March 2 - 6, 2023. During this competition, SFU and TACC participants will be presented with data challenges 
  and problems within the scope of cybersecurity, environmental, and social threats. This event offers a unique opportunity 
  for students to develop analytical and collaboration skills while connecting with leaders in research, industry, and government. 
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
