# Site Settings
baseurl: "/HacktheThreat23"

# Features Setting
# Turn subpages on or off
publications: False
resources: True
blog: False
schedule: True
organizers: True
codeofconduct: True 
projects: False

# Language of the website
lang: en

# Search engine optimization settings
title: Hack the Threat 2023
tagline: Cybersecurity, Enviromental, and Socal Threats Hackathon
description: < 
  The Texas Advanced Computer Center (TACC) is partnering with Simon Fraser University (SFU) to offer an engaging virtual 
  Hackathon from March 2 - 6, 2023. This event offers a unique opportunity for students to develop analytical and 
  collaboration skills while connecting with leaders in research, industry, and government.
author: HackHPC
twitter:
  username: ccloudhack
  card: Increasing understanding by harnessing the resources, skills and knowledge found in the HPC community.
logo: /assets/img/smile.png
social:
  name: HackHPC
  links:
    - mailto:schack@hackhcp.org
    - http://hackhpc.org/pasthacks
    - https://www.youtube.com/@hackhpc2069
    - https://www.linkedin.com/groups/8859728/
locale: en_US

# Page Settings
theme_settings:
  title: Hack the Threat 23

  experience_title: TIMELINE
  interests_title: EVENT SPONSORS
  skills_title: PARTICIPANTS
  awards_title: AWARDS
  projects_title: TEAM PROJECTS
  recentpubs_title: RECENT PUBLICATIONS

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Settings
sass:
  sass_dir: _sass
  style: :compressed
plugins: ['jekyll-paginate', 'jekyll/scholar', 'jekyll-seo-tag']
bootstrap:
  assets: true

# Bibliography settings
scholar:
  bibliography: publications.bib
  bibliography_template: pubstemplate
  style: apa
  locale: en
  last_name: Me
  first_name: [Myself, M.]
  sort_by: year,month
  order: descending,ascending

filtered_bibtex_keywords: [abbr, abstract, arxiv, bibtex_show, html, pdf, selected, supp, blog, code, poster, slides, website] # Filter out certain bibtex entry keywords used internally from the bib output

academicons:
  version: "1.9.1"
  integrity: "sha256-i1+4qU2G2860dGGIOJscdC30s9beBXjFfzjWLjBRsBg="
fontawesome:
  version: "5.15.4"
  integrity: "sha256-mUZM63G8m73Mcidfrv5E+Y61y7a12O5mW4ezU3bxqW4="
jquery:
  version: "3.6.0"
  integrity: "sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
